### ISSUE TITLE
Resources$NotFoundException na AdActivity

### ISSUE THREAD

**Issue by lucastsantos** [In-Loco-Media/inlocomedia-android-sdk#9]
Oi, pessoal.

Começamos a receber relatórios de crashes relacionados a classe `com.inlocomedia.android.ads.AdActivity`. 
Esse crash acontece apenas em devices da Motorola no Android 7.1.1

![image](https://user-images.githubusercontent.com/8331460/33219199-2f6099ee-d128-11e7-8c61-8392cd40a9ee.png)

Vocês podem dar uma olhada, por favor?

Algumas informações:

- TargetSdkVersion: 26

- Log do crash:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.studiosol.palcomp3/com.inlocomedia.android.ads.AdActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0d0000
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2825)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6339)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
Caused by android.content.res.Resources$NotFoundException: Resource ID #0x7f0d0000
       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
       at android.content.res.Resources.getDrawable(Resources.java:882)
       at android.content.Context.getDrawable(Context.java:530)
       at com.android.internal.widget.ToolbarWidgetWrapper.setIcon(ToolbarWidgetWrapper.java:322)
       at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:737)
       at com.android.internal.policy.PhoneWindow.setDefaultIcon(PhoneWindow.java:1757)
       at android.app.Activity.initWindowDecorActionBar(Activity.java:2406)
       at android.app.Activity.getActionBar(Activity.java:2339)
       at com.inlocomedia.android.ads.private.ag.onCreate(SourceCode:128)
       at android.app.Fragment.performCreate(Fragment.java:2336)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
       at android.app.BackStackRecord.setLastIn(BackStackRecord.java:860)
       at android.app.BackStackRecord.calculateFragments(BackStackRecord.java:883)
       at android.app.BackStackRecord.run(BackStackRecord.java:728)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1580)
       at android.app.FragmentController.execPendingActions(FragmentController.java:371)
       at android.app.Activity.performStart(Activity.java:6705)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2719)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2825)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6339)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
```

- Versões que utilizamos:
```
'com.inlocomedia.android:android-sdk-location:3.3.10'
'com.inlocomedia.android:android-sdk-engagement:3.3.10'
'com.inlocomedia.android:android-sdk-ads:3.3.10'
```

**Comment by pedroatanasio** [comment]
Lucas, obrigado por reportar o problema! 

Descobrimos que o crash acontece no nosso mini browser quando o resource do ícone do aplicativo não está presente. A correção estará disponível na versão 3.4 do SDK, mas desabilitamos remotamente o uso do mini browser nessa situação para que o crash não aconteça. Sendo assim, não é necessário realizar nenhuma ação por parte de vocês. Contornamos isso do nosso lado e os crashes devem parar.

Mais uma vez, obrigado!

**Comment by lucastsantos** [comment]
@pedroatansio Obrigado pela resposta rápida e detalhada 😄
